# Generated by Django 4.2.2 on 2025-09-08 02:52

import django.db.models.deletion
from django.db import migrations, models

import habits.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место, в котором необходимо выполнить привычку",
                        max_length=50,
                        null=True,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        default=habits.models.current_time,
                        help_text="Укажите время, когда необходимо выполнить привычку",
                        verbose_name="Время",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие, которое представляет собой привычка",
                        max_length=300,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "sign_of_pleasant_habit",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите, является ли эта привычка приятной",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=1,
                        help_text="Укажите периодичность выполнения привычки в днях",
                        null=True,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "award",
                    models.TextField(
                        blank=True,
                        help_text="Укажите вознаграждение после выполнения",
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.DurationField(
                        blank=True,
                        help_text="Укажите предположительное время на выполнение привычки",
                        null=True,
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "sign_of_publicity",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите, можно ли публиковать привычки в общий доступ",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите привычку, которая связанная с ПОЛЕЗНОЙ привычкой",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
