# Generated by Django 4.2.2 on 2025-09-09 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time_to_complete",
            field=models.DurationField(
                default=datetime.timedelta(seconds=60),
                help_text="Укажите предположительное время на выполнение привычки",
                verbose_name="Время на выполнение",
            ),
        ),
    ]
